<div id="carouselExampleIndicators" cl  ass="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img class="d-block w-100" src="img/barravelaLixo.jpeg" height="400px" alt="First slide">
            <div class="carousel-caption d-none d-md-block">
                <h2 style = "font-family: fantasy; color:#A13D2D; background-color:#C0C0C0; opacity:0.85">
                    Peso de     253 carros  de LIXO     descartados incorretamente por dia.
                </h2>
                <h5 style = "color:#A13D2D; background-color:#C0C0C0; opacity:0.7">
                    Diagnóstico preliminar de resíduos sólidos da cidade do rio de janeiro - 2015
                    (http://www.rio.rj.gov.br/dlstatic/10112/3372233/4149705/RelatorioExecutivoDiagnosticoPreliminar.pdf)
                </h5>
            </div>
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="img/avbrasilLixo.jpeg" height="400px" alt="Second slide">
            <div class="carousel-caption d-none d-md-block">
                <h2 style = "font-family: fantasy; color:#A13D2D; background-color:#C0C0C0; opacity:0.85">
                    “A disposição inadequada pode ocasionar poluição visual e a disseminação de doenças.”
                </h2>
                <h5 style = "color:#A13D2D; background-color:#C0C0C0; opacity:0.7">
                    Lixo, resíduos sólidos e reciclagem (https://www.scielo.br/pdf/er/n23/n23a18.pdf)
                </h5>
            </div>
        </div>
        <div class="carousel-item">
            <img class="d-block w-100" src="img/aimaraLixo.jpeg" height="400px" alt="Second slide">
            <div class="carousel-caption d-none d-md-block">
                <h2 style = "font-family: fantasy; color:#A13D2D; background-color:#C0C0C0; opacity:0.85">
                “Em virtude das condições de acesso, é possível aceitar que estes resíduos não sejam integralmente coletados.”
                </h2>
                <h5 style = "color:#A13D2D; background-color:#C0C0C0; opacity:0.7">
                    Diagnóstico preliminar de resíduos sólidos da cidade do rio de janeiro - 2015
                    (http://www.rio.rj.gov.br/dlstatic/10112/3372233/4149705/RelatorioExecutivoDiagnosticoPreliminar.pdf)
                </h5>
            </div>
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="container">
    <div class="row">
        <div class="col-lg-4">
            <img style="display:block; margin-left:auto; margin-right:auto;" 
            src="img/organicoAbrelpe.png" class="rounded-circle" alt="organico" width="140" height="140">
            <h3 style="text-align: center;">Tô pagaaando!!</h3>
            <p style="text-align: center;">
            TEXTO SOBRE LIXO ORGÂNICO
            </p>
        </div>
        <div class="col-lg-4">
            <img style="display:block; margin-left:auto; margin-right:auto;" 
            src="img/ods12Agenda2030.png" class="rounded-circle" alt="organico" width="140" height="140">
            <h3 style="text-align: center;">E eu com isso???</h3>
            <p style="text-align: center;">
            TEXTO SOBRE AS METAS E DESAFIOS
            </p>
        </div>
        <div class="col-lg-4">
            <img style="display:block; margin-left:auto; margin-right:auto;" 
            src="img/sustentaAbrelpe.png" class="rounded-circle" alt="organico" width="140" height="140">
            <h3 style="text-align: center;">O que me importa???</h3>
            <p style="text-align: center;">
            TEXTO SOBRE IMPORTÂNCIA DE AÇÕES PARA A SUSTENTABILIDADE
            </p>
        </div>
    </div>

</div>
