<div class="container mt-4">
    <div class="row">
        <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
                <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
                <div class="carousel-item active">
                    <img class="d-block w-100" src="img/barravelaLixo.jpeg" height="400px" alt="First slide">
                    <div class="carousel-caption d-none d-md-block">
                        <h2 style = "font-family: fantasy; color:#A13D2D; background-color:#C0C0C0; opacity:0.85">
                            Peso de     253 carros  de LIXO     descartados incorretamente por dia.
                        </h2>
                        <h5 style = "color:#A13D2D; background-color:#C0C0C0; opacity:0.7">
                            Diagnóstico preliminar de resíduos sólidos da cidade do rio de janeiro - 2015
                            (http://www.rio.rj.gov.br/dlstatic/10112/3372233/4149705/RelatorioExecutivoDiagnosticoPreliminar.pdf)
                        </h5>
                    </div>
                </div>
                <div class="carousel-item">
                    <img class="d-block w-100" src="img/avbrasilLixo.jpeg" height="400px" alt="Second slide">
                    <div class="carousel-caption d-none d-md-block">
                        <h2 style = "font-family: fantasy; color:#A13D2D; background-color:#C0C0C0; opacity:0.85">
                            “A disposição inadequada pode ocasionar poluição visual e a disseminação de doenças.”
                        </h2>
                        <h5 style = "color:#A13D2D; background-color:#C0C0C0; opacity:0.7">
                            Lixo, resíduos sólidos e reciclagem (https://www.scielo.br/pdf/er/n23/n23a18.pdf)
                        </h5>
                    </div>
                </div>
                <div class="carousel-item">
                    <img class="d-block w-100" src="img/aimaraLixo.jpeg" height="400px" alt="Second slide">
                    <div class="carousel-caption d-none d-md-block">
                        <h2 style = "font-family: fantasy; color:#A13D2D; background-color:#C0C0C0; opacity:0.85">
                        “Em virtude das condições de acesso, é possível aceitar que estes resíduos não sejam integralmente coletados.”
                        </h2>
                        <h5 style = "color:#A13D2D; background-color:#C0C0C0; opacity:0.7">
                            Diagnóstico preliminar de resíduos sólidos da cidade do rio de janeiro - 2015
                            (http://www.rio.rj.gov.br/dlstatic/10112/3372233/4149705/RelatorioExecutivoDiagnosticoPreliminar.pdf)
                        </h5>
                    </div>
                </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
</div>

<div class="container">
    <div class="row mt-1">
        <div class="col-lg-4">
            <img style="display:block; margin-left:auto; margin-right:auto;" 
            src="img/organicoAbrelpe.png" class="rounded-circle" alt="organico" width="140" height="140">
            <h4 style="text-align: center;">Tô pagaaando!!</h4>
        </div>
        <div class="col-lg-4">
            <img style="display:block; margin-left:auto; margin-right:auto;" 
            src="img/ods12Agenda2030.png" class="rounded-circle" alt="organico" width="140" height="140">
            <h4 style="text-align: center;">E eu com isso???</h4>
        </div>
        <div class="col-lg-4">
            <img style="display:block; margin-left:auto; margin-right:auto;" 
            src="img/sustentaAbrelpe.png" class="rounded-circle" alt="organico" width="140" height="140">
            <h4 style="text-align: center;">Será que tem jeito???</h4>
        </div>
    </div>

</div>
<hr>
<div class="container">
    <div class="row" style="height:400px;">
        <div class="col-md-6 d-flex">
            <div class="align-self-center animeRight">
                <h2>Matéria Orgânica</h2>
                <h4>Sobras e perdas de alimentos, resíduos verdes e madeiras.</h4>
                <p>Panorama dos Resíduos Sólidos no Brasil 2020 - Abrelpe</p>
            </div>
        </div>
        <div class="col-md-6 d-none d-md-block">
            <img  class="animeLeft img-fluid rounded" src="/img/dadosorganicoAbrelpe.png" alt="dadosorganico">
        </div>
    </div>
</div>
<hr>
<div class="container">
    <div class="row" style="height:400px;">
        <div class="col-md-6  d-none d-md-block">
            <img  class="animeRight img-fluid rounded" src="/img/ods12IBGE.jpeg" alt="">
        </div>
        <div class="col-md-6 d-flex">
            <div class="align-self-center animeLeft">
                <h2>Agenda 2030 - Metas ODS 12</h2>
                <h5>12.5 Reduzir a geração de resíduos;</h5>
                <h5>12.8 Informação relevante e conscientização sobre o desenvolvimento
                 sustentável e estilos de vida em harmonia com a natureza.</h5>
                <p>http://www.agenda2030.org.br/ods/12/</p>
                <p>https://agenciadenoticias.ibge.gov.br/agencia-noticias/2012-agencia-de-noticias/noticias/19062-ods-12-consumo-e-producao-conscientes</p>
            </div>
        </div>
    </div>
</div>
<hr>
<div class="container">
    <div class="row" style="height:400px;">
        <div class="col-md-6  d-none d-md-block">
            <img  class="animeRight img-fluid rounded" src="/img/urgenciaAbrelpe.png" alt="">
        </div>
        <div class="col-md-6 d-flex mt-3">
            <div class="animeLeft">
                <h2>Urgência de Soluções</h2>
                <h5>"Mantendo-se o cenário atual seriam necessários 55 anos para que aterros 
                controlados e lixões sejam encerrados. Há urgência de soluções para viabilizar
                as ações necessárias, de forma contínua e com sustentabilidade."
                </h5> 
                <p>Panorama dos Resíduos Sólidos no Brasil 2020 - Abrelpe</p>
                
            </div>
        </div>
    </div>
</div>
