<div class="container">
    <?php if($this->view->UsuarioSalvo == true){ ?>
        <div class="row">
                <div class="col-md-12">
                    <button class="btn btn-success btn-lg w-100 mb-4">Atualização efetuada com sucesso!</button>
                </div>
        <div>
    <?php } ?>

    <div class="row justify-content-center align-items-center formulario">
    
        <div class="col-md-5">
            
            <fieldset>
                <legend class="h1 titulo-ins">Editar Cadastro</legend>
                <form class="row g-3 form" action="/atualizar" method="post">
                    <div class="col-md-12">
                     
                        <input style="width:300px;" type="text" name="nome" placeholder="Nome Completo" class="form-control" id="inputEmail4">
                    </div>
    
                    <div class="col-md-12">
                    
                        <input style="width:300px;" type="password" name="senha" placeholder="Senha" class="form-control" id="inputPassword4">
                    </div>
                    <div class="col-md-12">
                      
                        <input style="width:300px;" type="password" name="csenha" placeholder="Confirmar Senha" class="form-control" id="inputPassword4">
                    </div>
                    <div class="col-md-12">
                        <input type="text" style="width:200px;" name="cep" class="form-control" id="inputCity" placeholder="Cep">
    
                    </div>
                    <div class="col-md-12">
                        <input style="width:200px;" type="text"  name="numero" class="form-control" id="inputCity" placeholder="Número">
                    </div>
    
                    <div class="col-md-12">
                        <input style="width:200px;" type="text" name="cidade" class="form-control" id="inputCity" placeholder="Cidade">
                    </div>
                    <div class="col-12">
    
                        <input style="width:400px;" type="text"  name="endereco" class="form-control" id="inputAddress" placeholder="Endereço">
                    </div>
                    <div class="col-12">
    
                        <input style="width:300px;" type="text" name="complemento" class="form-control" id="inputAddress2" placeholder="Complemento">
                    </div>
    
    
                    <div class="col-12">
                        <button type="submit" class="btn btn-primary w-100">Cadastrar</button>
                    </div>
                </form>
            </fieldset>
        </div>
    </div>
    
</div>

