
        <div class="wrapper">
        <!-- Sidebar -->
        <nav id="sidebar">
            <div class="sidebar-header">
                <h3>Bootstrap Sidebar</h3>
            </div>
    
            <ul class="list-unstyled components">
                <p>Dummy Heading</p>
                <li class="active">
                    <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Home</a>
                    <ul class="collapse list-unstyled" id="homeSubmenu">
                        <li>
                            <a href="#">Home 1</a>
                        </li>
                        <li>
                            <a href="#">Home 2</a>
                        </li>
                        <li>
                            <a href="#">Home 3</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#">About</a>
                </li>
                <li>
                    <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Pages</a>
                    <ul class="collapse list-unstyled" id="pageSubmenu">
                        <li>
                            <a href="#">Page 1</a>
                        </li>
                        <li>
                            <a href="#">Page 2</a>
                        </li>
                        <li>
                            <a href="#">Page 3</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="#">Portfolio</a>
                </li>
                <li>
                    <a href="#">Contact</a>
                </li>
            </ul>
        </nav>
        <div id="content">
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container-fluid">
        
                    <button type="button" id="sidebarCollapse" class="btn btn-info">
                        <i class="fas fa-align-left"></i>
                        
                    </button>
        
                </div>
            </nav>
            <!--Conteudo a ser modificado-->
            <div id="conteudo">
                <nav class="navbar navbar-expand-lg menu">
                    <div class="container">
                      <div class="navbar-nav">
                          <a class="menuItem" href="/timeline">
                              Home
                          </a>
                
                          <a class="menuItem" href="/sair">
                              Sair
                          </a>
                            <img src="/img/twitter_logo.png" class="menuIco" />
                      </div>
                    </div>
                </nav>
                
                <div class="render">
                    <div class="conteudo-rende container mt-5">
                        <div class="row pt-2">
                            
                            <div class="col-md-3">
                    
                                <div class="perfil">
                                    <div class="perfilTopo">
                    
                                    </div>
                    
                                    <div class="perfilPainel">
                                        
                                        <div class="row mt-2 mb-2">
                                            <div class="col mb-2">
                                                <span class="perfilPainelNome">Nome do Usuário</span>
                                            </div>
                                        </div>
                    
                                        <div class="row mb-2">
                    
                                            <div class="col">
                                                <span class="perfilPainelItem">Tweets</span><br />
                                                <span class="perfilPainelItemValor">0</span>
                                            </div>
                    
                                            <div class="col">
                                                <span class="perfilPainelItem">Seguindo</span><br />
                                                <span class="perfilPainelItemValor">0</span>
                                            </div>
                    
                                            <div class="col">
                                                <span class="perfilPainelItem">Seguidores</span><br />
                                                <span class="perfilPainelItemValor">0</span>
                                            </div>
                    
                                        </div>
                    
                                    </div>
                                </div>
                    
                            </div>
                    
                            <div class="col-md-6">
                                <div class="row mb-2">
                                    <div class="col tweetBox">
            
                                            <textarea  class="form-control texto-mutira" id="exampleFormControlTextarea1" rows="3"></textarea>
                                            
                                            <div class="col mt-2 d-flex justify-content-end">
                                                <button id="btn-salvar"type="submit" class="btn btn-primary">Mutirar</button>
                                            </div>
                    
                                       
                                    </div>
                                </div>
                                <?php foreach($this->view->mutiras as $id_mutira => $mutira){ ?>
                                    <div class="row tweet">
                                        <div class="col">
                                        
                                            <p><strong><?php echo $mutira['nome_usuario']?></strong> <span class="text text-muted"><?php echo $mutira['data']?></span></p>
                                            <p><?php echo $mutira['mutira']?></p>
                        
                                            <br />
                                            
                                                <div class="col d-flex justify-content-end">
                                                    <button type="" class="btn btn-danger btn-remove" value="<?php echo $mutira['mutira']?>"><small>Remover</small></button>
                                                </div>
                                            
                                        </div>
                                    </div>
                                <?php }?>
            
                    
                    
                            </div>
                    
                    
                            <div class="col-md-3">
                                <div class="quemSeguir">
                                    <span class="quemSeguirTitulo">Quem seguir</span><br />
                                    <hr />
                                    <a href="#" class="quemSeguirTxt">Procurar por pessoas conhecidas</a>
                                </div>
                            </div>
                    
                        </div>
                    </div>
                </div>
            </div>
                </div>
    
    </div>
        
        <!-- paginas -->
		<div class="main" id="pagina">
        </div>
