<html>
	<head>
		<meta charset="utf-8" />
		<title>Miniframework</title>

		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

		<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
		<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
		<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

		<link rel="stylesheet" type="text/css" href="/css/style.css">
		<link rel="stylesheet" type="text/css" href="/css/footer/footer.css">
		<link rel="stylesheet" type="text/css" href="/css/cadastro/formulario.css">
		<link rel="stylesheet" type="text/css" href="/css/App/timeline/timeline.css">
        <link rel="stylesheet" type="text/css" href="/css/App/mutirae/mutirae.css">
        
        <script src="./js/timeline/timeline.js"></script>
        <script src="./js/timeline/removeMutiroes.js"></script>

        <style>
            .block:hover{
                cursor:not-allowed ;
            }
        </style>

    </header>

    <body>
		
	<div class="wrapper">
        <!-- Sidebar -->
        <nav id="sidebar">
            <div class="sidebar-header">
            <div class="row justify-content-center ">
                <img src="img/together-w.png" style="width:50px; height:50px;"class="mr-3" />
                    <h3>Menu</h3>
            </div>
            </div>
    
            <ul class="list-unstyled components">
            
                <li>
                    <a id="mutiras"href="/Appmutira">Mutirões</a>
                </li>
                <li>
                    <a id="rede"href="/Apprede">Rede</a>
                </li>
                <li>
                    <a id="perfil"href="/perfil">Perfil</a>
                    
                </li>
                
                <li>
                    <a  class="block" href="#">Configurações</a>
                </li>
                <li>
                    <a  class="block" href="#">Contato</a>
                </li >
                <li>
                    <a  class="block" href="#">Calendário</a>
                </li>
                <li >
                    <a href="#pageSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle block">Ajuda</a>
                    <ul class="collapse list-unstyled" id="pageSubmenu">
                        <li>
                        
                        </li>
                       
                    </ul>
                </li>
            </ul>
        </nav>
    
        <div id="content">
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container-fluid">
        
                    <button type="button" id="sidebarCollapse" class="btn btn-info">
                        <i class="fas fa-align-left"></i>
                        
                    </button>
        
                </div>
            </nav>
            <!--Conteudo a ser modificado-->
            <div id="conteudo">
                <nav class="navbar navbar-expand-lg menu">
                    <div class="container">
                      <div class="navbar-nav">
                          <a class="menuItem" href="/timeline">
                              Home
                          </a>
                
                          <a class="menuItem" href="/sair">
                              Sair
                          </a>
                           
                      </div>
                    </div>
                </nav>
                <div class="render">
				<?= $this->content() ?>
                </div>
            </div>
            
        </div>

    
</div>
        
    <!-- paginas -->

    </body>
</html>